version: '3.8'

services:
  web:
    build: .
    env_file: dev.env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file: dev.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    expose:
      - 5432


volumes:
  postgres_data_dev:



